#! /bin/bash
set -eu

#
# Globals
#

ROOT="$(git -C "$(readlink -f "$(dirname "${0}")")" rev-parse --show-toplevel)"
DIRS=(gitignore)

source "${ROOT}/globals"

#
# Functions
#

function list_gitignores() {
  local dir
  local key
  local file
  local remote
  local url
  local branch
  local host
  local acct
  local repo
  for dir in "${DIRS[@]}"; do
    if [ -d "${dir}" ]; then
      while read -r file; do
        key="$(echo "${file,,}" |
              sed -e "s,${dir}/,,g" |
              sed -e "s,^\./,,g" -e "s,community/,,g" -e "s,global/,,g" -e "s,/,_,g" |
              sed -n "s,\(.*\).gitignore,\1,p")"
        branch="$(git -C "$(dirname "${file}")" rev-parse --abbrev-ref HEAD)"
        remote="$(git -C "$(dirname "${file}")" remote get-url --all origin)"
        repo="$(basename "${remote}" | sed -e "s/\.git$//g")"
        host="$(dirname "${remote}")"
        acct="$(basename "${host}")"
        host="$(dirname "${host}")"
        case "${host}" in
          https://github.com | github.com)
            host="https://raw.githubusercontent.com"
            url="${host}/${acct}/${repo}/${branch}/$(basename "${file}")"
            ;;
          https://gitlab.com | gitlab.com)
            host="https://gitlab.com"
            url="${host}/${acct}/${repo}/-/raw/${branch}/$(basename "${file}")"
            ;;
          https://codeberg.org | codeberg.org)
            host="https://codeberg.org"
            url="${host}/${acct}/${repo}/raw/branch/${branch}/$(basename "${file}")"
            ;;
          *)
            show_error "WARNING: ${file@Q} unsupported. Skipping."
            continue
            ;;
        esac
        echo "FILE[${key@Q}]=${file@Q}"
        echo "URL[${key@Q}]=${url@Q}"
        echo
      done <<< "$(find "./${dir}" -type f -name "*.gitignore" | sort -d -f)"
    fi
  done
}

function print_header() {
  cat << EOF
#! /bin/bash

#
# WARNING: This file is auto-generated. Do not edit manually.
#

declare -A FILE
declare -A URL

EOF
}

function print_footer() {
  cat << EOF
export FILE
export URL
EOF
}

#
# Main
#

pushd "${ROOT}" > /dev/null

print_header
list_gitignores
print_footer
